version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "go run main.go"
    container_name: app-container
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8040:8040
